services:
  db-to-bq:
    build: .
    container_name: db-to-bq-test
    env_file:
      - .env
    volumes:
      - ./prj-davar-p-bq-a01c-1b6c1d59b2b7.json:/app/creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds.json
    # Mode interactif pour voir les logs dlt en temps r√©el
    stdin_open: true
    tty: true
